[functions.deduct-credit]
enabled = true
verify_jwt = true
import_map = "./functions/deduct-credit/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deduct-credit/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deduct-credit/*.html" ]

[functions.check-credit]
enabled = true
verify_jwt = true
import_map = "./functions/check-credit/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-credit/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-credit/*.html" ]

[functions.notify-payment]
enabled = true
verify_jwt = false
import_map = "./functions/notify-payment/deno.json"
entrypoint = "./functions/notify-payment/index.ts"

[functions.notify-admin-telegram]
enabled = true
verify_jwt = false
import_map = "./functions/notify-admin-telegram/deno.json"
entrypoint = "./functions/notify-admin-telegram/index.ts"

[functions.telegram-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/telegram-webhook/deno.json"
entrypoint = "./functions/telegram-webhook/index.ts"
